
# SEO settings
title: "Darlene Zouras - Comfy Coding v2"
title2: "" # default: ""
description: "Just another minimalist Jekyll theme that focuses on technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://darzouras.me # site url
baseurl: /blog # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "heiswayi"
twitter_username: "darzouras"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Darlene Zouras"
  job      : "Newbie Developer"
  bio      : "Artist, Educator, and Developer."
  thumb    : null
  email    : dzouras@gmail.com
  url      : http://darzouras.me
  github   : http://github.com/darzouras
  twitter  : http://twitter.com/darzouras
  facebook : https://www.facebook.com/darlene.zouras
  linkedin : http://linkedin.com/in/darlenezouras

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@darzouras"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
